---
language: node_js
sudo: required
dist: trusty
cache:
  directories:
    - node_modules
node_js:
  - 6
  - 5

after_success:
  - npm run integration

after_script:
  - npm install -g codecov
  - codecov
